### PR TITLE
Comment unterminated line

### LINKED ISSUE #1: Invalid syntax
When I try to run the script, it crashes because of an invalid syntax
```
  File "applebarn_v3_0_0.py", line 53
    elif day ==
              ^
SyntaxError: invalid syntax
```

### PR DESCRIPTION
**Pull request by Zeg9**
This fixes #1

### CODE REVIEW

**Comment by Applebarn** [comment]
no

**Comment by Zeg9** [comment]
:crying_cat_face:

**Comment by Zeg9** [comment]
:cry: :sob: :fu:

**Comment by Zeg9** [comment]
Why?

**Pull request closed without merging**
